### ISSUE TITLE
Remove autotools build

### ISSUE THREAD

**Issue by mlund** [mlund/spheretree#4]
#3 adds support for building with CMake and we can thus remove the autotools build which seems to be broken on e.g. MacOS and possible other targets. Ping @ZhouYixuanRobtic. For software archeological reasons the old-style build is preserved in the git history.

**Comment by mlund** [comment]
> I'll work on this. I've tried the old-style build, and with a newly-created README file, the tool can work properly on my LINUX system. Although, I don't have an available MAC, so I cannot test it on MacOS. Can we just fix this and create a new branch for some users may use this classic tool?

Yes, we can just create a tag for the initial import from 10 year ago ;-)

**Comment by ZhouYixuanRobtic** [comment]
Sorry about late reply (and work). I'm living in China, so we may have 8
hours latency.  Salute to your excellent work.

Mikael Lund ***@***.***> 于2024年10月23日周三 05:18写道：
